### ISSUE TITLE
CU:Solicitar Reporte de Ventas

### ISSUE THREAD

**Issue by cmcm21** [ADOO21/Documento-de-analisis#25]

**Comment by quevangel** [comment]
En este sí siento que está de sobra eso de "ver si valió la pena invertir en el sistema".

**Comment by quevangel** [comment]
Podría ser más bien "Conocer la dirección general de la empresa" o algo parecido, pero eso de si valió el sistema no sería un objetivo del Actor siempre.

**Comment by cmcm21** [comment]
tienes toda la razón me suena más lógico ese.
