### ISSUE TITLE
CU:Listar creditos de clientes

### ISSUE THREAD

**Issue by cmcm21** [ADOO21/Documento-de-analisis#29]

**Comment by quevangel** [comment]
¿A qué nos referimos como "contenido"?

**Comment by quevangel** [comment]
@cmcm21

**Comment by cmcm21** [comment]
me equivoque en el titulo

**Comment by quevangel** [comment]
Ok.

**Comment by cmcm21** [comment]
como que siento que este caso de uso no tienen un proposito claro, como vez @quevangel ?

**Comment by quevangel** [comment]
Yo tampoco veo un propósito claro.

**Comment by cmcm21** [comment]
entonces lo hay que quitarlo

**Comment by quevangel** [comment]
Pero eso causa problemas con la numeración de Casos de Uso.

**Comment by quevangel** [comment]
No había pensado en eso cuando propuse poner los números en el diagrama.
