### ISSUE TITLE
CU23: Abrir turno de Caja

### ISSUE THREAD

**Issue by quevangel** [ADOO21/Documento-de-analisis#3]

**Comment by quevangel** [comment]
@cmcm21 En este me cuesta trabajo formular el propósito.

**Comment by quevangel** [comment]
Digo, sé que el Supervisor lo que quiere es iniciar el registro de ventas.

**Comment by quevangel** [comment]
¿Para controlar los tiempos de venta?

**Comment by cmcm21** [comment]
tal vez para tener un mejor control de los ingresos?

**Comment by quevangel** [comment]
¿Entonces este y cerrar turno de caja tendrían el mismo propósito?

**Comment by cmcm21** [comment]
no, no pueden tener el mismo propósito dos CU deferentes.
pude ser algo como. Controlar la puntualidad y empezar a registrar la actividad de la farmacia?

**Comment by quevangel** [comment]
¿Se controla la puntualidad? ¿De quién?

**Comment by cmcm21** [comment]
Es que el propósito tiene que responder a la pregunta ¿para que se inician los registros de ventas?.
si no se responde no es un caso de uso.
otra posibilidad podría ser para poder realizar ventas y registrar estas en el sistema?

**Comment by quevangel** [comment]
Sí, tiene que ver con el registro de ventas, eso sí tiene un propósito claro.
Pero ¿Por qué no registrar ventas sin abrir/cerrar caja?

**Comment by quevangel** [comment]
¿Por qué no se abre/cierra automáticamente?

**Comment by cmcm21** [comment]
por que ya es una regla del negocio, es algo que el profe pidió y también quiere que sea controlado por el supervisor

**Comment by quevangel** [comment]
Entonces, creo que para el supervisor es propósito suficiente querer registrar la hora de inicio/fin de actividades de la sucursal, con el fin de reportarse esta información al dueño o simplemente cumplir con la normatividad ¿No?

**Comment by cmcm21** [comment]
si es eso. me gusta

**Comment by quevangel** [comment]
Ahora ¿Cómo sabrá el sistema qué sucursal está abriendo caja? Supongo que eso estaría implícito dependiendo de la computadora/dispositvo que se use al hacer eso.

**Comment by cmcm21** [comment]
Si asi es
