### ISSUE TITLE
CU10: Aplicar el Crédito del Cliente.

### ISSUE THREAD

**Issue by quevangel** [ADOO21/Documento-de-analisis#32]

**Comment by quevangel** [comment]
@cmcm21 No lo ví agregado antes. Y tampoco lo veo implementado en https://github.com/ADOO21/Documento-de-analisis/blob/master/cu/cus.tex

**Comment by cmcm21** [comment]
ese caso de uso aun no se hace

**Comment by quevangel** [comment]
¿Entonces sí faltaba agregar el Issue?

**Comment by quevangel** [comment]
Problema de nombres. Está resuelto.
