### ISSUE TITLE
No veo diferencia entre CU Agregar Credito a un Cliente y CU Darle Credito a un Cliente

### ISSUE THREAD

**Issue by quevangel** [ADOO21/Documento-de-analisis#33]

**Comment by quevangel** [comment]
https://github.com/ADOO21/Documento-de-analisis/issues/27
https://github.com/ADOO21/Documento-de-analisis/issues/15

Parecen estar duplicados.

**Comment by quevangel** [comment]
De hecho https://github.com/ADOO21/Documento-de-analisis/issues/27 no está en el diagrama.

**Comment by cmcm21** [comment]
disculpa me equivoque en los nombres, uno es aplicar el credito de cliente, que es cuado le hacemos una devolucion y le cambiamos el medicamento por otro, o que el credito que tiene lo use para comprar un medicamento.
el otro 'Darle credito a un cliente' es aumentarle el credito al cliente, o cuando pida una devolución y no quiera cambiar el producto por uno nuevo, entonces guardamos ese dinero del medicamento que compro estropeado, como credito

**Comment by quevangel** [comment]
Ah, ya entiendo.
Eso hace innecesario el https://github.com/ADOO21/Documento-de-analisis/issues/32#issuecomment-383320143.
Lo eliminaré.

**Comment by cmcm21** [comment]
gracias por la observación
