### ISSUE TITLE
CU36: Recuperar Contraseña

### ISSUE THREAD

**Issue by quevangel** [ADOO21/Documento-de-analisis#8]

**Comment by quevangel** [comment]
@cmcm21 Tenemos que ponernos de acuerdo en cómo se hará esto.

**Comment by quevangel** [comment]
Creo que lo apropiado es que se mandara un reporte al supervisor.

**Comment by cmcm21** [comment]
si creo que por mensaje seria correcto, pero siento que sera más al dueño que al supervisor. 
ya que el dueño es el que registra a los empleados, cuando el liste a los empleados apareceran sus datos y entre sus datos esta su contraseña

**Comment by quevangel** [comment]
Ok, entonces, un mensaje al Dueño y ya.

**Comment by quevangel** [comment]
Casi casi solo sería eso.
Que en el login, diga un botón "No recuerdo mi contraseña" y entonces el sistema diga que ya fue reportado al Dueño o ¿Algo así?

**Comment by cmcm21** [comment]
Si algo asi podria ser. Perdon por tardar no lo habia visto xD
